// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWP_Xamarin_Hotel_API.Models.DB;

namespace SWP_Xamarin_Hotel_API.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.AdditionalService", b =>
                {
                    b.Property<int>("AdditionalServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StandardPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("AdditionalServiceId");

                    b.ToTable("AdditionalServices");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BeginReservation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EndReservation")
                        .HasColumnType("datetime");

                    b.Property<string>("GuestPassportNumber")
                        .HasColumnType("varchar(767)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("BillId");

                    b.HasIndex("GuestPassportNumber");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Bills_AdditionalServices", b =>
                {
                    b.Property<int>("Bills_AdditionalServicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdditionalServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<float>("Discount")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GuestPassportNumber")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Bills_AdditionalServicesId");

                    b.HasIndex("AdditionalServiceId");

                    b.HasIndex("BillId");

                    b.HasIndex("GuestPassportNumber");

                    b.ToTable("Bills_AdditionalServices");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Bills_Rooms", b =>
                {
                    b.Property<int>("Bills_RoomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<float>("Discount")
                        .HasColumnType("float");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Bills_RoomsId");

                    b.HasIndex("BillId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bills_Rooms");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Guest", b =>
                {
                    b.Property<string>("PassportNumber")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PassportNumber");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Guests_Addresses", b =>
                {
                    b.Property<int>("Guests_AddressesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("GuestPassportNumber")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Guests_AddressesId");

                    b.HasIndex("AddressId");

                    b.HasIndex("GuestPassportNumber");

                    b.ToTable("Guests_Addresses");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("HasBalcony")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasKitchen")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasTerrace")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumberOfBeds")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Bill", b =>
                {
                    b.HasOne("SWP_Xamarin_Hotel_API.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestPassportNumber");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Bills_AdditionalServices", b =>
                {
                    b.HasOne("SWP_Xamarin_Hotel_API.Models.AdditionalService", "AdditionalService")
                        .WithMany()
                        .HasForeignKey("AdditionalServiceId");

                    b.HasOne("SWP_Xamarin_Hotel_API.Models.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId");

                    b.HasOne("SWP_Xamarin_Hotel_API.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestPassportNumber");

                    b.Navigation("AdditionalService");

                    b.Navigation("Bill");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Bills_Rooms", b =>
                {
                    b.HasOne("SWP_Xamarin_Hotel_API.Models.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId");

                    b.HasOne("SWP_Xamarin_Hotel_API.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.Navigation("Bill");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SWP_Xamarin_Hotel_API.Models.Guests_Addresses", b =>
                {
                    b.HasOne("SWP_Xamarin_Hotel_API.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("SWP_Xamarin_Hotel_API.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestPassportNumber");

                    b.Navigation("Address");

                    b.Navigation("Guest");
                });
#pragma warning restore 612, 618
        }
    }
}
